version: "3"

tasks:
  pre:
    cmds:
      - mkdir -p bin

  clean:
    deps:
      - pre
    cmds:
      - rm -rf bin/*

  build:
    deps:
      - pre
    cmds:
      - GOOS=windows GOARCH=amd64 go build -o bin/main.exe main.go

  run:
    cmds:
      - go run main.go
